version: 1.0.{build}
image: Visual Studio 2019
install:
 - ps: $env:JAVA_HOME="C:\Program Files\Java\jdk11"
 - dotnet tool install --global dotnet-sonarscanner
before_build:
 - dotnet sonarscanner begin /k:"MarkMenchavez_Utilities" /d:"sonar.host.url=https://sonarcloud.io" /o:"markmenchavez" /d:sonar.login="110896645303739d9fae44092d397ac35d29bd08" /v:1.0 /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.coverage.exclusions="**Test*.cs"
build_script:
 - dotnet restore -f -v m
 - dotnet build --no-restore --nologo -c Release 
 - dotnet test --no-build --nologo -v m -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_build:
 - dotnet sonarscanner end /d:sonar.login="110896645303739d9fae44092d397ac35d29bd08"